version: '3' 
services: 
  api: 
    build: 
      dockerfile: Dockerfile.dev 
      contexte: ./server 
    volumes: 
      - / app  
      - ./server:/app 
  client: 
    build: 
      dockerfile: Dockerfile.dev 
      context : ./client 
    volumes: 
      - / app / node_modules 
      - ./client:/app 
  nginx: 
    restart: toujours 
    build: 
      dockerfile: Dockerfile.dev 
      contexte: ./nginx 
    ports: 
      - '8080: 80'