version: "3"
services: 
    app:
        container_name: app
        restart: always
        build: ./api
        ports:
            - "4000:4000"
    client:
        build: 
            dockerfile: Dockerfile.dev
        context: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - ./client:/app
        
    
           